# Generated by Django 2.0.6 on 2018-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='opcoes',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(default=11, upload_to='imagem', verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resp_correta',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
