# Generated by Django 2.0.6 on 2018-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180910_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resp_errada1',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resp_errada2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
