# Generated by Django 2.0 on 2018-09-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180910_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relaciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='resp_correta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='resp_errada1',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='resp_errada2',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='relaciona',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='core.Relaciona'),
            preserve_default=False,
        ),
    ]
