# Generated by Django 2.0 on 2018-09-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180916_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaciona',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='relaciona',
            name='alt_1',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relaciona',
            name='ir_para',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.Pergunta'),
            preserve_default=False,
        ),
    ]
