# Generated by Django 2.0.6 on 2018-09-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180916_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaciona',
            name='alt_1',
        ),
        migrations.AlterField(
            model_name='relaciona',
            name='ir_para',
            field=models.ForeignKey(help_text='ir', on_delete=django.db.models.deletion.CASCADE, to='core.Pergunta'),
        ),
    ]
