# Generated by Django 2.0.8 on 2018-09-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180918_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciona',
            name='ir_para',
            field=models.ForeignKey(help_text='Esse campo serve para direcionar para qual pergunta deve ter as opções', on_delete=django.db.models.deletion.CASCADE, to='core.Pergunta'),
        ),
        migrations.AlterField(
            model_name='relaciona',
            name='relaciona',
            field=models.ForeignKey(help_text='Esse campo serve para mostrar em qual pergunta o botão deve aparecer para        se relacionar com a pergunta de cima', on_delete=django.db.models.deletion.CASCADE, related_name='relacionas', to='core.Pergunta'),
        ),
    ]
