# Generated by Django 2.0.8 on 2018-09-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180918_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='imagem',
        ),
    ]
